"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `abstractMethodSignatureNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptAbstractMethodSignature` | |
| `abstractMethodSignatureReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptAbstractMethodSignature` | |
| `addingTypeAnnotationOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptAddingTypeAnnotation` | |
| `ambientDeclarationOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptAmbientDeclaration` | |
| `argumentsOwner` | `FASTTEntity` | `argumentsList` | `FASTTypeScriptArguments` | The arguments node that owns me|
| `arrayOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptArray` | |
| `arrayPatternOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptArrayPattern` | |
| `arrayTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptArrayType` | |
| `arrowFunctionBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptArrowFunction` | My owner|
| `arrowFunctionReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptArrowFunction` | |
| `asExpressionOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptAsExpression` | |
| `assertsAnnotationOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptAssertsAnnotation` | |
| `assertsOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptAsserts` | |
| `augmentedAssignmentExpressionOperatorOwner` | `FASTTypeScriptEntity` | `operator` | `FASTTypeScriptAugmentedAssignmentExpression` | |
| `awaitExpressionOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptAwaitExpression` | |
| `binaryExpressionOperatorOwner` | `FASTTypeScriptEntity` | `operator` | `FASTTypeScriptBinaryExpression` | |
| `callExpressionArgumentsOwner` | `FASTTypeScriptEntity` | `arguments` | `FASTTypeScriptCallExpression` | |
| `callExpressionFunctionOwner` | `FASTTypeScriptEntity` | `function` | `FASTTypeScriptCallExpression` | |
| `callSignatureReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptCallSignature` | |
| `catchClauseParameterOwner` | `FASTTypeScriptEntity` | `parameter` | `FASTTypeScriptCatchClause` | |
| `classHeritageOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptClassHeritage` | |
| `computedPropertyNameOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptComputedPropertyName` | |
| `constraintOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptConstraint` | |
| `decoratorOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptDecorator` | |
| `defaultTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptDefaultType` | |
| `elseClauseOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptElseClause` | |
| `enumAssignmentNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptEnumAssignment` | |
| `enumBodyNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptEnumBody` | |
| `exportClauseOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptExportClause` | |
| `expressionStatementOwner` | `FASTTypeScriptEntity` | `expression` | `FASTTypeScriptExpressionStatement` | |
| `flowMaybeTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptFlowMaybeType` | |
| `forInStatementKindOwner` | `FASTTypeScriptEntity` | `kind` | `FASTTypeScriptForInStatement` | |
| `forInStatementOperatorOwner` | `FASTTypeScriptEntity` | `operator` | `FASTTypeScriptForInStatement` | |
| `forStatementConditionOwner` | `FASTTypeScriptEntity` | `condition` | `FASTTypeScriptForStatement` | |
| `forStatementIncrementOwner` | `FASTTypeScriptEntity` | `increment` | `FASTTypeScriptForStatement` | |
| `forStatementInitializerOwner` | `FASTTypeScriptEntity` | `initializer` | `FASTTypeScriptForStatement` | |
| `functionExpressionReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptFunctionExpression` | |
| `functionSignatureReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptFunctionSignature` | |
| `generatorFunctionDeclarationReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptGeneratorFunctionDeclaration` | |
| `generatorFunctionReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptGeneratorFunction` | |
| `genericParent` | `FASTTypeScriptEntity` | `genericChildren` | `FASTTypeScriptEntity` | |
| `implementsClauseOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptImplementsClause` | |
| `importAliasOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptImportAlias` | |
| `importAttributeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptImportAttribute` | |
| `importClauseOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptImportClause` | |
| `indexSignatureSignOwner` | `FASTTypeScriptEntity` | `sign` | `FASTTypeScriptIndexSignature` | |
| `indexTypeQueryOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptIndexTypeQuery` | |
| `inferTypeOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptInferType` | |
| `instantiationExpressionFunctionOwner` | `FASTTypeScriptEntity` | `function` | `FASTTypeScriptInstantiationExpression` | |
| `interfaceBodyOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptInterfaceBody` | |
| `internalModuleNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptInternalModule` | |
| `intersectionTypeOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptIntersectionType` | |
| `lexicalDeclarationKindOwner` | `FASTTypeScriptEntity` | `kind` | `FASTTypeScriptLexicalDeclaration` | |
| `literalTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptLiteralType` | |
| `lookupTypeOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptLookupType` | |
| `methodSignatureNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptMethodSignature` | |
| `methodSignatureReturnTypeOwner` | `FASTTypeScriptEntity` | `return_type` | `FASTTypeScriptMethodSignature` | |
| `moduleNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptModule` | |
| `namedImportsOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptNamedImports` | |
| `namespaceExportOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptNamespaceExport` | |
| `namespaceImportOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptNamespaceImport` | |
| `nestedTypeIdentifierModuleOwner` | `FASTTypeScriptEntity` | `module` | `FASTTypeScriptNestedTypeIdentifier` | |
| `nonNullExpressionOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptNonNullExpression` | |
| `objectAssignmentPatternLeftOwner` | `FASTTypeScriptEntity` | `left` | `FASTTypeScriptObjectAssignmentPattern` | |
| `objectOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptObject` | |
| `objectPatternOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptObjectPattern` | |
| `objectTypeOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptObjectType` | |
| `omittingTypeAnnotationOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptOmittingTypeAnnotation` | |
| `optingTypeAnnotationOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptOptingTypeAnnotation` | |
| `optionalTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptOptionalType` | |
| `pairKeyOwner` | `FASTTypeScriptEntity` | `key` | `FASTTypeScriptPair` | |
| `pairPatternKeyOwner` | `FASTTypeScriptEntity` | `key` | `FASTTypeScriptPairPattern` | |
| `pairPatternValueOwner` | `FASTTypeScriptEntity` | `value` | `FASTTypeScriptPairPattern` | |
| `parentFormalParameters` | `FASTTEntity` | `parameters` | `FASTTypeScriptFormalParameters` | My owner|
| `parenthesizedTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptParenthesizedType` | |
| `programOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptProgram` | |
| `propertySignatureNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptPropertySignature` | |
| `publicFieldDefinitionNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptPublicFieldDefinition` | |
| `readonlyTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptReadonlyType` | |
| `requiredParameterNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptRequiredParameter` | |
| `restPatternOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptRestPattern` | |
| `restTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptRestType` | |
| `returnStatementOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptReturnStatement` | |
| `satisfiesExpressionOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptSatisfiesExpression` | |
| `sequenceExpressionOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptSequenceExpression` | |
| `spreadElementOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptSpreadElement` | |
| `statementBlockOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptStatementBlock` | |
| `stringOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptString` | |
| `switchBodyOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptSwitchBody` | |
| `switchCaseValueOwner` | `FASTTypeScriptEntity` | `value` | `FASTTypeScriptSwitchCase` | |
| `templateLiteralTypeOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptTemplateLiteralType` | |
| `templateStringOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptTemplateString` | |
| `templateSubstitutionOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptTemplateSubstitution` | |
| `templateTypeOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptTemplateType` | |
| `throwStatementOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptThrowStatement` | |
| `tupleTypeOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptTupleType` | |
| `typeAnnotationOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptTypeAnnotation` | |
| `typeArgumentsOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptTypeArguments` | |
| `typeAssertionOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptTypeAssertion` | |
| `typeParametersOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptTypeParameters` | |
| `typeQueryOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptTypeQuery` | |
| `unaryExpressionOperatorOwner` | `FASTTypeScriptEntity` | `operator` | `FASTTypeScriptUnaryExpression` | |
| `unionTypeOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptUnionType` | |
| `updateExpressionOperatorOwner` | `FASTTypeScriptEntity` | `operator` | `FASTTypeScriptUpdateExpression` | |
| `variableDeclarationOwner` | `FASTTypeScriptEntity` | `childrenNodes` | `FASTTypeScriptVariableDeclaration` | |
| `variableDeclaratorNameOwner` | `FASTTypeScriptEntity` | `name` | `FASTTypeScriptVariableDeclarator` | |
| `yieldExpressionOwner` | `FASTTypeScriptEntity` | `childrenNode` | `FASTTypeScriptYieldExpression` | |

### Children
| Relation | Origin | Opposite | Type | Comment |
|---|
| `comments` | `FASTTWithComments` | `container` | `FASTTComment` | list of comments defined in the entity|
| `genericChildren` | `FASTTypeScriptEntity` | `genericParent` | `FASTTypeScriptEntity` | |


## Properties
======================

| Name | Type | Default value | Comment |
|---|
| `endPos` | `Number` | nil | |
| `startPos` | `Number` | nil | |

"
Class {
	#name : 'FASTTypeScriptEntity',
	#superclass : 'MooseEntity',
	#traits : 'FASTTEntity + FASTTWithComments + TEntityMetaLevelDependency',
	#classTraits : 'FASTTEntity classTrait + FASTTWithComments classTrait + TEntityMetaLevelDependency classTrait',
	#instVars : [
		'#abstractMethodSignatureNameOwner => FMOne type: #FASTTypeScriptAbstractMethodSignature opposite: #name',
		'#abstractMethodSignatureReturnTypeOwner => FMOne type: #FASTTypeScriptAbstractMethodSignature opposite: #return_type',
		'#addingTypeAnnotationOwner => FMOne type: #FASTTypeScriptAddingTypeAnnotation opposite: #childrenNode',
		'#ambientDeclarationOwner => FMOne type: #FASTTypeScriptAmbientDeclaration opposite: #childrenNodes',
		'#arrayOwner => FMOne type: #FASTTypeScriptArray opposite: #childrenNodes',
		'#arrayPatternOwner => FMOne type: #FASTTypeScriptArrayPattern opposite: #childrenNodes',
		'#arrayTypeOwner => FMOne type: #FASTTypeScriptArrayType opposite: #childrenNode',
		'#arrowFunctionReturnTypeOwner => FMOne type: #FASTTypeScriptArrowFunction opposite: #return_type',
		'#asExpressionOwner => FMOne type: #FASTTypeScriptAsExpression opposite: #childrenNodes',
		'#assertsAnnotationOwner => FMOne type: #FASTTypeScriptAssertsAnnotation opposite: #childrenNode',
		'#assertsOwner => FMOne type: #FASTTypeScriptAsserts opposite: #childrenNode',
		'#augmentedAssignmentExpressionOperatorOwner => FMOne type: #FASTTypeScriptAugmentedAssignmentExpression opposite: #operator',
		'#awaitExpressionOwner => FMOne type: #FASTTypeScriptAwaitExpression opposite: #childrenNode',
		'#binaryExpressionOperatorOwner => FMOne type: #FASTTypeScriptBinaryExpression opposite: #operator',
		'#callExpressionArgumentsOwner => FMOne type: #FASTTypeScriptCallExpression opposite: #arguments',
		'#callExpressionFunctionOwner => FMOne type: #FASTTypeScriptCallExpression opposite: #function',
		'#callSignatureReturnTypeOwner => FMOne type: #FASTTypeScriptCallSignature opposite: #return_type',
		'#catchClauseParameterOwner => FMOne type: #FASTTypeScriptCatchClause opposite: #parameter',
		'#classHeritageOwner => FMOne type: #FASTTypeScriptClassHeritage opposite: #childrenNodes',
		'#computedPropertyNameOwner => FMOne type: #FASTTypeScriptComputedPropertyName opposite: #childrenNode',
		'#constraintOwner => FMOne type: #FASTTypeScriptConstraint opposite: #childrenNode',
		'#decoratorOwner => FMOne type: #FASTTypeScriptDecorator opposite: #childrenNode',
		'#defaultTypeOwner => FMOne type: #FASTTypeScriptDefaultType opposite: #childrenNode',
		'#elseClauseOwner => FMOne type: #FASTTypeScriptElseClause opposite: #childrenNode',
		'#enumAssignmentNameOwner => FMOne type: #FASTTypeScriptEnumAssignment opposite: #name',
		'#enumBodyNameOwner => FMOne type: #FASTTypeScriptEnumBody opposite: #name',
		'#exportClauseOwner => FMOne type: #FASTTypeScriptExportClause opposite: #childrenNodes',
		'#expressionStatementOwner => FMOne type: #FASTTypeScriptExpressionStatement opposite: #expression',
		'#flowMaybeTypeOwner => FMOne type: #FASTTypeScriptFlowMaybeType opposite: #childrenNode',
		'#forInStatementKindOwner => FMOne type: #FASTTypeScriptForInStatement opposite: #kind',
		'#forInStatementOperatorOwner => FMOne type: #FASTTypeScriptForInStatement opposite: #operator',
		'#forStatementConditionOwner => FMOne type: #FASTTypeScriptForStatement opposite: #condition',
		'#forStatementIncrementOwner => FMOne type: #FASTTypeScriptForStatement opposite: #increment',
		'#forStatementInitializerOwner => FMOne type: #FASTTypeScriptForStatement opposite: #initializer',
		'#functionExpressionReturnTypeOwner => FMOne type: #FASTTypeScriptFunctionExpression opposite: #return_type',
		'#functionSignatureReturnTypeOwner => FMOne type: #FASTTypeScriptFunctionSignature opposite: #return_type',
		'#generatorFunctionDeclarationReturnTypeOwner => FMOne type: #FASTTypeScriptGeneratorFunctionDeclaration opposite: #return_type',
		'#generatorFunctionReturnTypeOwner => FMOne type: #FASTTypeScriptGeneratorFunction opposite: #return_type',
		'#genericChildren => FMMany type: #FASTTypeScriptEntity opposite: #genericParent',
		'#genericParent => FMOne type: #FASTTypeScriptEntity opposite: #genericChildren',
		'#implementsClauseOwner => FMOne type: #FASTTypeScriptImplementsClause opposite: #childrenNodes',
		'#importAliasOwner => FMOne type: #FASTTypeScriptImportAlias opposite: #childrenNodes',
		'#importAttributeOwner => FMOne type: #FASTTypeScriptImportAttribute opposite: #childrenNode',
		'#importClauseOwner => FMOne type: #FASTTypeScriptImportClause opposite: #childrenNodes',
		'#indexSignatureSignOwner => FMOne type: #FASTTypeScriptIndexSignature opposite: #sign',
		'#indexTypeQueryOwner => FMOne type: #FASTTypeScriptIndexTypeQuery opposite: #childrenNode',
		'#inferTypeOwner => FMOne type: #FASTTypeScriptInferType opposite: #childrenNodes',
		'#instantiationExpressionFunctionOwner => FMOne type: #FASTTypeScriptInstantiationExpression opposite: #function',
		'#interfaceBodyOwner => FMOne type: #FASTTypeScriptInterfaceBody opposite: #childrenNodes',
		'#internalModuleNameOwner => FMOne type: #FASTTypeScriptInternalModule opposite: #name',
		'#intersectionTypeOwner => FMOne type: #FASTTypeScriptIntersectionType opposite: #childrenNodes',
		'#lexicalDeclarationKindOwner => FMOne type: #FASTTypeScriptLexicalDeclaration opposite: #kind',
		'#literalTypeOwner => FMOne type: #FASTTypeScriptLiteralType opposite: #childrenNode',
		'#lookupTypeOwner => FMOne type: #FASTTypeScriptLookupType opposite: #childrenNodes',
		'#methodSignatureNameOwner => FMOne type: #FASTTypeScriptMethodSignature opposite: #name',
		'#methodSignatureReturnTypeOwner => FMOne type: #FASTTypeScriptMethodSignature opposite: #return_type',
		'#moduleNameOwner => FMOne type: #FASTTypeScriptModule opposite: #name',
		'#namedImportsOwner => FMOne type: #FASTTypeScriptNamedImports opposite: #childrenNodes',
		'#namespaceExportOwner => FMOne type: #FASTTypeScriptNamespaceExport opposite: #childrenNode',
		'#namespaceImportOwner => FMOne type: #FASTTypeScriptNamespaceImport opposite: #childrenNode',
		'#nestedTypeIdentifierModuleOwner => FMOne type: #FASTTypeScriptNestedTypeIdentifier opposite: #module',
		'#nonNullExpressionOwner => FMOne type: #FASTTypeScriptNonNullExpression opposite: #childrenNode',
		'#objectAssignmentPatternLeftOwner => FMOne type: #FASTTypeScriptObjectAssignmentPattern opposite: #left',
		'#objectOwner => FMOne type: #FASTTypeScriptObject opposite: #childrenNodes',
		'#objectPatternOwner => FMOne type: #FASTTypeScriptObjectPattern opposite: #childrenNodes',
		'#objectTypeOwner => FMOne type: #FASTTypeScriptObjectType opposite: #childrenNodes',
		'#omittingTypeAnnotationOwner => FMOne type: #FASTTypeScriptOmittingTypeAnnotation opposite: #childrenNode',
		'#optingTypeAnnotationOwner => FMOne type: #FASTTypeScriptOptingTypeAnnotation opposite: #childrenNode',
		'#optionalTypeOwner => FMOne type: #FASTTypeScriptOptionalType opposite: #childrenNode',
		'#pairKeyOwner => FMOne type: #FASTTypeScriptPair opposite: #key',
		'#pairPatternKeyOwner => FMOne type: #FASTTypeScriptPairPattern opposite: #key',
		'#pairPatternValueOwner => FMOne type: #FASTTypeScriptPairPattern opposite: #value',
		'#parenthesizedTypeOwner => FMOne type: #FASTTypeScriptParenthesizedType opposite: #childrenNode',
		'#programOwner => FMOne type: #FASTTypeScriptProgram opposite: #childrenNodes',
		'#propertySignatureNameOwner => FMOne type: #FASTTypeScriptPropertySignature opposite: #name',
		'#publicFieldDefinitionNameOwner => FMOne type: #FASTTypeScriptPublicFieldDefinition opposite: #name',
		'#readonlyTypeOwner => FMOne type: #FASTTypeScriptReadonlyType opposite: #childrenNode',
		'#requiredParameterNameOwner => FMOne type: #FASTTypeScriptRequiredParameter opposite: #name',
		'#restPatternOwner => FMOne type: #FASTTypeScriptRestPattern opposite: #childrenNode',
		'#restTypeOwner => FMOne type: #FASTTypeScriptRestType opposite: #childrenNode',
		'#returnStatementOwner => FMOne type: #FASTTypeScriptReturnStatement opposite: #childrenNode',
		'#satisfiesExpressionOwner => FMOne type: #FASTTypeScriptSatisfiesExpression opposite: #childrenNodes',
		'#sequenceExpressionOwner => FMOne type: #FASTTypeScriptSequenceExpression opposite: #childrenNodes',
		'#spreadElementOwner => FMOne type: #FASTTypeScriptSpreadElement opposite: #childrenNode',
		'#statementBlockOwner => FMOne type: #FASTTypeScriptStatementBlock opposite: #childrenNodes',
		'#stringOwner => FMOne type: #FASTTypeScriptString opposite: #childrenNodes',
		'#switchBodyOwner => FMOne type: #FASTTypeScriptSwitchBody opposite: #childrenNodes',
		'#switchCaseValueOwner => FMOne type: #FASTTypeScriptSwitchCase opposite: #value',
		'#templateLiteralTypeOwner => FMOne type: #FASTTypeScriptTemplateLiteralType opposite: #childrenNodes',
		'#templateStringOwner => FMOne type: #FASTTypeScriptTemplateString opposite: #childrenNodes',
		'#templateSubstitutionOwner => FMOne type: #FASTTypeScriptTemplateSubstitution opposite: #childrenNode',
		'#templateTypeOwner => FMOne type: #FASTTypeScriptTemplateType opposite: #childrenNode',
		'#throwStatementOwner => FMOne type: #FASTTypeScriptThrowStatement opposite: #childrenNode',
		'#tupleTypeOwner => FMOne type: #FASTTypeScriptTupleType opposite: #childrenNodes',
		'#typeAnnotationOwner => FMOne type: #FASTTypeScriptTypeAnnotation opposite: #childrenNode',
		'#typeArgumentsOwner => FMOne type: #FASTTypeScriptTypeArguments opposite: #childrenNodes',
		'#typeAssertionOwner => FMOne type: #FASTTypeScriptTypeAssertion opposite: #childrenNodes',
		'#typeParametersOwner => FMOne type: #FASTTypeScriptTypeParameters opposite: #childrenNodes',
		'#typeQueryOwner => FMOne type: #FASTTypeScriptTypeQuery opposite: #childrenNode',
		'#unaryExpressionOperatorOwner => FMOne type: #FASTTypeScriptUnaryExpression opposite: #operator',
		'#unionTypeOwner => FMOne type: #FASTTypeScriptUnionType opposite: #childrenNodes',
		'#updateExpressionOperatorOwner => FMOne type: #FASTTypeScriptUpdateExpression opposite: #operator',
		'#variableDeclarationOwner => FMOne type: #FASTTypeScriptVariableDeclaration opposite: #childrenNodes',
		'#variableDeclaratorNameOwner => FMOne type: #FASTTypeScriptVariableDeclarator opposite: #name',
		'#yieldExpressionOwner => FMOne type: #FASTTypeScriptYieldExpression opposite: #childrenNode'
	],
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptEntity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FASTTypeScriptEntity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FASTTypeScriptEntity
]

{ #category : 'meta' }
FASTTypeScriptEntity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FASTTypeScriptModel metamodel
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> abstractMethodSignatureNameOwner [
	"Relation named: #abstractMethodSignatureNameOwner type: #FASTTypeScriptAbstractMethodSignature opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ abstractMethodSignatureNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> abstractMethodSignatureNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	abstractMethodSignatureNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> abstractMethodSignatureReturnTypeOwner [
	"Relation named: #abstractMethodSignatureReturnTypeOwner type: #FASTTypeScriptAbstractMethodSignature opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ abstractMethodSignatureReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> abstractMethodSignatureReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	abstractMethodSignatureReturnTypeOwner := anObject
]

{ #category : 'adding' }
FASTTypeScriptEntity >> addGenericChild: anObject [

	<ignoreForCoverage>
	<generated>
	^ self genericChildren add: anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> addingTypeAnnotationOwner [
	"Relation named: #addingTypeAnnotationOwner type: #FASTTypeScriptAddingTypeAnnotation opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ addingTypeAnnotationOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> addingTypeAnnotationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	addingTypeAnnotationOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> ambientDeclarationOwner [
	"Relation named: #ambientDeclarationOwner type: #FASTTypeScriptAmbientDeclaration opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ ambientDeclarationOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> ambientDeclarationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	ambientDeclarationOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrayOwner [
	"Relation named: #arrayOwner type: #FASTTypeScriptArray opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ arrayOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrayOwner: anObject [

	<ignoreForCoverage>
	<generated>
	arrayOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrayPatternOwner [
	"Relation named: #arrayPatternOwner type: #FASTTypeScriptArrayPattern opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ arrayPatternOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrayPatternOwner: anObject [

	<ignoreForCoverage>
	<generated>
	arrayPatternOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrayTypeOwner [
	"Relation named: #arrayTypeOwner type: #FASTTypeScriptArrayType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ arrayTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrayTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	arrayTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrowFunctionReturnTypeOwner [
	"Relation named: #arrowFunctionReturnTypeOwner type: #FASTTypeScriptArrowFunction opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ arrowFunctionReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> arrowFunctionReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	arrowFunctionReturnTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> asExpressionOwner [
	"Relation named: #asExpressionOwner type: #FASTTypeScriptAsExpression opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ asExpressionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> asExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	asExpressionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> assertsAnnotationOwner [
	"Relation named: #assertsAnnotationOwner type: #FASTTypeScriptAssertsAnnotation opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ assertsAnnotationOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> assertsAnnotationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	assertsAnnotationOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> assertsOwner [
	"Relation named: #assertsOwner type: #FASTTypeScriptAsserts opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ assertsOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> assertsOwner: anObject [

	<ignoreForCoverage>
	<generated>
	assertsOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> augmentedAssignmentExpressionOperatorOwner [
	"Relation named: #augmentedAssignmentExpressionOperatorOwner type: #FASTTypeScriptAugmentedAssignmentExpression opposite: #operator"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ augmentedAssignmentExpressionOperatorOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> augmentedAssignmentExpressionOperatorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	augmentedAssignmentExpressionOperatorOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> awaitExpressionOwner [
	"Relation named: #awaitExpressionOwner type: #FASTTypeScriptAwaitExpression opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ awaitExpressionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> awaitExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	awaitExpressionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> binaryExpressionOperatorOwner [
	"Relation named: #binaryExpressionOperatorOwner type: #FASTTypeScriptBinaryExpression opposite: #operator"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ binaryExpressionOperatorOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> binaryExpressionOperatorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	binaryExpressionOperatorOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> callExpressionArgumentsOwner [
	"Relation named: #callExpressionArgumentsOwner type: #FASTTypeScriptCallExpression opposite: #arguments"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ callExpressionArgumentsOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> callExpressionArgumentsOwner: anObject [

	<ignoreForCoverage>
	<generated>
	callExpressionArgumentsOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> callExpressionFunctionOwner [
	"Relation named: #callExpressionFunctionOwner type: #FASTTypeScriptCallExpression opposite: #function"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ callExpressionFunctionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> callExpressionFunctionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	callExpressionFunctionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> callSignatureReturnTypeOwner [
	"Relation named: #callSignatureReturnTypeOwner type: #FASTTypeScriptCallSignature opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ callSignatureReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> callSignatureReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	callSignatureReturnTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> catchClauseParameterOwner [
	"Relation named: #catchClauseParameterOwner type: #FASTTypeScriptCatchClause opposite: #parameter"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ catchClauseParameterOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> catchClauseParameterOwner: anObject [

	<ignoreForCoverage>
	<generated>
	catchClauseParameterOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> classHeritageOwner [
	"Relation named: #classHeritageOwner type: #FASTTypeScriptClassHeritage opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ classHeritageOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> classHeritageOwner: anObject [

	<ignoreForCoverage>
	<generated>
	classHeritageOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> computedPropertyNameOwner [
	"Relation named: #computedPropertyNameOwner type: #FASTTypeScriptComputedPropertyName opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ computedPropertyNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> computedPropertyNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	computedPropertyNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> constraintOwner [
	"Relation named: #constraintOwner type: #FASTTypeScriptConstraint opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ constraintOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> constraintOwner: anObject [

	<ignoreForCoverage>
	<generated>
	constraintOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> decoratorOwner [
	"Relation named: #decoratorOwner type: #FASTTypeScriptDecorator opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ decoratorOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> decoratorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	decoratorOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> defaultTypeOwner [
	"Relation named: #defaultTypeOwner type: #FASTTypeScriptDefaultType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ defaultTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> defaultTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	defaultTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> elseClauseOwner [
	"Relation named: #elseClauseOwner type: #FASTTypeScriptElseClause opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ elseClauseOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> elseClauseOwner: anObject [

	<ignoreForCoverage>
	<generated>
	elseClauseOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> enumAssignmentNameOwner [
	"Relation named: #enumAssignmentNameOwner type: #FASTTypeScriptEnumAssignment opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ enumAssignmentNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> enumAssignmentNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	enumAssignmentNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> enumBodyNameOwner [
	"Relation named: #enumBodyNameOwner type: #FASTTypeScriptEnumBody opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	^ enumBodyNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> enumBodyNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	enumBodyNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> exportClauseOwner [
	"Relation named: #exportClauseOwner type: #FASTTypeScriptExportClause opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ exportClauseOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> exportClauseOwner: anObject [

	<ignoreForCoverage>
	<generated>
	exportClauseOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> expressionStatementOwner [
	"Relation named: #expressionStatementOwner type: #FASTTypeScriptExpressionStatement opposite: #expression"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ expressionStatementOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> expressionStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	expressionStatementOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> flowMaybeTypeOwner [
	"Relation named: #flowMaybeTypeOwner type: #FASTTypeScriptFlowMaybeType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ flowMaybeTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> flowMaybeTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	flowMaybeTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forInStatementKindOwner [
	"Relation named: #forInStatementKindOwner type: #FASTTypeScriptForInStatement opposite: #kind"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ forInStatementKindOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forInStatementKindOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forInStatementKindOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forInStatementOperatorOwner [
	"Relation named: #forInStatementOperatorOwner type: #FASTTypeScriptForInStatement opposite: #operator"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ forInStatementOperatorOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forInStatementOperatorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forInStatementOperatorOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forStatementConditionOwner [
	"Relation named: #forStatementConditionOwner type: #FASTTypeScriptForStatement opposite: #condition"

	<ignoreForCoverage>
	<generated>
	<container>
	^ forStatementConditionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forStatementConditionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forStatementConditionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forStatementIncrementOwner [
	"Relation named: #forStatementIncrementOwner type: #FASTTypeScriptForStatement opposite: #increment"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ forStatementIncrementOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forStatementIncrementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forStatementIncrementOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forStatementInitializerOwner [
	"Relation named: #forStatementInitializerOwner type: #FASTTypeScriptForStatement opposite: #initializer"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ forStatementInitializerOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> forStatementInitializerOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forStatementInitializerOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> functionExpressionReturnTypeOwner [
	"Relation named: #functionExpressionReturnTypeOwner type: #FASTTypeScriptFunctionExpression opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ functionExpressionReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> functionExpressionReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	functionExpressionReturnTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> functionSignatureReturnTypeOwner [
	"Relation named: #functionSignatureReturnTypeOwner type: #FASTTypeScriptFunctionSignature opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ functionSignatureReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> functionSignatureReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	functionSignatureReturnTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> generatorFunctionDeclarationReturnTypeOwner [
	"Relation named: #generatorFunctionDeclarationReturnTypeOwner type: #FASTTypeScriptGeneratorFunctionDeclaration opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ generatorFunctionDeclarationReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> generatorFunctionDeclarationReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	generatorFunctionDeclarationReturnTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> generatorFunctionReturnTypeOwner [
	"Relation named: #generatorFunctionReturnTypeOwner type: #FASTTypeScriptGeneratorFunction opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ generatorFunctionReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> generatorFunctionReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	generatorFunctionReturnTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> genericChildren [
	"Relation named: #genericChildren type: #FASTTypeScriptEntity opposite: #genericParent"

	<ignoreForCoverage>
	<generated>
	<derived>
	^ genericChildren
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> genericChildren: anObject [

	<ignoreForCoverage>
	<generated>
	genericChildren value: anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> genericParent [
	"Relation named: #genericParent type: #FASTTypeScriptEntity opposite: #genericChildren"

	<ignoreForCoverage>
	<generated>
	<container>
	^ genericParent
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> genericParent: anObject [

	<ignoreForCoverage>
	<generated>
	genericParent := anObject
]

{ #category : 'testing' }
FASTTypeScriptEntity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> implementsClauseOwner [
	"Relation named: #implementsClauseOwner type: #FASTTypeScriptImplementsClause opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ implementsClauseOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> implementsClauseOwner: anObject [

	<ignoreForCoverage>
	<generated>
	implementsClauseOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> importAliasOwner [
	"Relation named: #importAliasOwner type: #FASTTypeScriptImportAlias opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ importAliasOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> importAliasOwner: anObject [

	<ignoreForCoverage>
	<generated>
	importAliasOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> importAttributeOwner [
	"Relation named: #importAttributeOwner type: #FASTTypeScriptImportAttribute opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ importAttributeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> importAttributeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	importAttributeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> importClauseOwner [
	"Relation named: #importClauseOwner type: #FASTTypeScriptImportClause opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ importClauseOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> importClauseOwner: anObject [

	<ignoreForCoverage>
	<generated>
	importClauseOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> indexSignatureSignOwner [
	"Relation named: #indexSignatureSignOwner type: #FASTTypeScriptIndexSignature opposite: #sign"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ indexSignatureSignOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> indexSignatureSignOwner: anObject [

	<ignoreForCoverage>
	<generated>
	indexSignatureSignOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> indexTypeQueryOwner [
	"Relation named: #indexTypeQueryOwner type: #FASTTypeScriptIndexTypeQuery opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ indexTypeQueryOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> indexTypeQueryOwner: anObject [

	<ignoreForCoverage>
	<generated>
	indexTypeQueryOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> inferTypeOwner [
	"Relation named: #inferTypeOwner type: #FASTTypeScriptInferType opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ inferTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> inferTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	inferTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> instantiationExpressionFunctionOwner [
	"Relation named: #instantiationExpressionFunctionOwner type: #FASTTypeScriptInstantiationExpression opposite: #function"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ instantiationExpressionFunctionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> instantiationExpressionFunctionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	instantiationExpressionFunctionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> interfaceBodyOwner [
	"Relation named: #interfaceBodyOwner type: #FASTTypeScriptInterfaceBody opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ interfaceBodyOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> interfaceBodyOwner: anObject [

	<ignoreForCoverage>
	<generated>
	interfaceBodyOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> internalModuleNameOwner [
	"Relation named: #internalModuleNameOwner type: #FASTTypeScriptInternalModule opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ internalModuleNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> internalModuleNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	internalModuleNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> intersectionTypeOwner [
	"Relation named: #intersectionTypeOwner type: #FASTTypeScriptIntersectionType opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ intersectionTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> intersectionTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	intersectionTypeOwner := anObject
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isBooleanLiteral [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isClassDeclaration [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isCompilationUnit [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isEnumDeclaration [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isExpression [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isExpressionStatement [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isLiteral [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isNullPointerLiteral [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isStatement [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FASTTypeScriptEntity >> isStringLiteral [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> lexicalDeclarationKindOwner [
	"Relation named: #lexicalDeclarationKindOwner type: #FASTTypeScriptLexicalDeclaration opposite: #kind"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ lexicalDeclarationKindOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> lexicalDeclarationKindOwner: anObject [

	<ignoreForCoverage>
	<generated>
	lexicalDeclarationKindOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> literalTypeOwner [
	"Relation named: #literalTypeOwner type: #FASTTypeScriptLiteralType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ literalTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> literalTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	literalTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> lookupTypeOwner [
	"Relation named: #lookupTypeOwner type: #FASTTypeScriptLookupType opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ lookupTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> lookupTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	lookupTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> methodSignatureNameOwner [
	"Relation named: #methodSignatureNameOwner type: #FASTTypeScriptMethodSignature opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ methodSignatureNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> methodSignatureNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	methodSignatureNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> methodSignatureReturnTypeOwner [
	"Relation named: #methodSignatureReturnTypeOwner type: #FASTTypeScriptMethodSignature opposite: #return_type"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ methodSignatureReturnTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> methodSignatureReturnTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	methodSignatureReturnTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> moduleNameOwner [
	"Relation named: #moduleNameOwner type: #FASTTypeScriptModule opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ moduleNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> moduleNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	moduleNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> namedImportsOwner [
	"Relation named: #namedImportsOwner type: #FASTTypeScriptNamedImports opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ namedImportsOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> namedImportsOwner: anObject [

	<ignoreForCoverage>
	<generated>
	namedImportsOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> namespaceExportOwner [
	"Relation named: #namespaceExportOwner type: #FASTTypeScriptNamespaceExport opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ namespaceExportOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> namespaceExportOwner: anObject [

	<ignoreForCoverage>
	<generated>
	namespaceExportOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> namespaceImportOwner [
	"Relation named: #namespaceImportOwner type: #FASTTypeScriptNamespaceImport opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ namespaceImportOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> namespaceImportOwner: anObject [

	<ignoreForCoverage>
	<generated>
	namespaceImportOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> nestedTypeIdentifierModuleOwner [
	"Relation named: #nestedTypeIdentifierModuleOwner type: #FASTTypeScriptNestedTypeIdentifier opposite: #module"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ nestedTypeIdentifierModuleOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> nestedTypeIdentifierModuleOwner: anObject [

	<ignoreForCoverage>
	<generated>
	nestedTypeIdentifierModuleOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> nonNullExpressionOwner [
	"Relation named: #nonNullExpressionOwner type: #FASTTypeScriptNonNullExpression opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ nonNullExpressionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> nonNullExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	nonNullExpressionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectAssignmentPatternLeftOwner [
	"Relation named: #objectAssignmentPatternLeftOwner type: #FASTTypeScriptObjectAssignmentPattern opposite: #left"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ objectAssignmentPatternLeftOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectAssignmentPatternLeftOwner: anObject [

	<ignoreForCoverage>
	<generated>
	objectAssignmentPatternLeftOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectOwner [
	"Relation named: #objectOwner type: #FASTTypeScriptObject opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ objectOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectOwner: anObject [

	<ignoreForCoverage>
	<generated>
	objectOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectPatternOwner [
	"Relation named: #objectPatternOwner type: #FASTTypeScriptObjectPattern opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ objectPatternOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectPatternOwner: anObject [

	<ignoreForCoverage>
	<generated>
	objectPatternOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectTypeOwner [
	"Relation named: #objectTypeOwner type: #FASTTypeScriptObjectType opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ objectTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> objectTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	objectTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> omittingTypeAnnotationOwner [
	"Relation named: #omittingTypeAnnotationOwner type: #FASTTypeScriptOmittingTypeAnnotation opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ omittingTypeAnnotationOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> omittingTypeAnnotationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	omittingTypeAnnotationOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> optingTypeAnnotationOwner [
	"Relation named: #optingTypeAnnotationOwner type: #FASTTypeScriptOptingTypeAnnotation opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ optingTypeAnnotationOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> optingTypeAnnotationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	optingTypeAnnotationOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> optionalTypeOwner [
	"Relation named: #optionalTypeOwner type: #FASTTypeScriptOptionalType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ optionalTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> optionalTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	optionalTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> pairKeyOwner [
	"Relation named: #pairKeyOwner type: #FASTTypeScriptPair opposite: #key"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ pairKeyOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> pairKeyOwner: anObject [

	<ignoreForCoverage>
	<generated>
	pairKeyOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> pairPatternKeyOwner [
	"Relation named: #pairPatternKeyOwner type: #FASTTypeScriptPairPattern opposite: #key"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ pairPatternKeyOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> pairPatternKeyOwner: anObject [

	<ignoreForCoverage>
	<generated>
	pairPatternKeyOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> pairPatternValueOwner [
	"Relation named: #pairPatternValueOwner type: #FASTTypeScriptPairPattern opposite: #value"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ pairPatternValueOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> pairPatternValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	pairPatternValueOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> parenthesizedTypeOwner [
	"Relation named: #parenthesizedTypeOwner type: #FASTTypeScriptParenthesizedType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ parenthesizedTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> parenthesizedTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	parenthesizedTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> programOwner [
	"Relation named: #programOwner type: #FASTTypeScriptProgram opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ programOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> programOwner: anObject [

	<ignoreForCoverage>
	<generated>
	programOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> propertySignatureNameOwner [
	"Relation named: #propertySignatureNameOwner type: #FASTTypeScriptPropertySignature opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ propertySignatureNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> propertySignatureNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	propertySignatureNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> publicFieldDefinitionNameOwner [
	"Relation named: #publicFieldDefinitionNameOwner type: #FASTTypeScriptPublicFieldDefinition opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ publicFieldDefinitionNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> publicFieldDefinitionNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	publicFieldDefinitionNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> readonlyTypeOwner [
	"Relation named: #readonlyTypeOwner type: #FASTTypeScriptReadonlyType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ readonlyTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> readonlyTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	readonlyTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> requiredParameterNameOwner [
	"Relation named: #requiredParameterNameOwner type: #FASTTypeScriptRequiredParameter opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ requiredParameterNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> requiredParameterNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	requiredParameterNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> restPatternOwner [
	"Relation named: #restPatternOwner type: #FASTTypeScriptRestPattern opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ restPatternOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> restPatternOwner: anObject [

	<ignoreForCoverage>
	<generated>
	restPatternOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> restTypeOwner [
	"Relation named: #restTypeOwner type: #FASTTypeScriptRestType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ restTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> restTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	restTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> returnStatementOwner [
	"Relation named: #returnStatementOwner type: #FASTTypeScriptReturnStatement opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ returnStatementOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> returnStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	returnStatementOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> satisfiesExpressionOwner [
	"Relation named: #satisfiesExpressionOwner type: #FASTTypeScriptSatisfiesExpression opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ satisfiesExpressionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> satisfiesExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	satisfiesExpressionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> sequenceExpressionOwner [
	"Relation named: #sequenceExpressionOwner type: #FASTTypeScriptSequenceExpression opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ sequenceExpressionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> sequenceExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	sequenceExpressionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> spreadElementOwner [
	"Relation named: #spreadElementOwner type: #FASTTypeScriptSpreadElement opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ spreadElementOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> spreadElementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	spreadElementOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> statementBlockOwner [
	"Relation named: #statementBlockOwner type: #FASTTypeScriptStatementBlock opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ statementBlockOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> statementBlockOwner: anObject [

	<ignoreForCoverage>
	<generated>
	statementBlockOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> stringOwner [
	"Relation named: #stringOwner type: #FASTTypeScriptString opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ stringOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> stringOwner: anObject [

	<ignoreForCoverage>
	<generated>
	stringOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> switchBodyOwner [
	"Relation named: #switchBodyOwner type: #FASTTypeScriptSwitchBody opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ switchBodyOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> switchBodyOwner: anObject [

	<ignoreForCoverage>
	<generated>
	switchBodyOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> switchCaseValueOwner [
	"Relation named: #switchCaseValueOwner type: #FASTTypeScriptSwitchCase opposite: #value"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ switchCaseValueOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> switchCaseValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	switchCaseValueOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateLiteralTypeOwner [
	"Relation named: #templateLiteralTypeOwner type: #FASTTypeScriptTemplateLiteralType opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ templateLiteralTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateLiteralTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	templateLiteralTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateStringOwner [
	"Relation named: #templateStringOwner type: #FASTTypeScriptTemplateString opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ templateStringOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateStringOwner: anObject [

	<ignoreForCoverage>
	<generated>
	templateStringOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateSubstitutionOwner [
	"Relation named: #templateSubstitutionOwner type: #FASTTypeScriptTemplateSubstitution opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ templateSubstitutionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateSubstitutionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	templateSubstitutionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateTypeOwner [
	"Relation named: #templateTypeOwner type: #FASTTypeScriptTemplateType opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ templateTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> templateTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	templateTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> throwStatementOwner [
	"Relation named: #throwStatementOwner type: #FASTTypeScriptThrowStatement opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ throwStatementOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> throwStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	throwStatementOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> tupleTypeOwner [
	"Relation named: #tupleTypeOwner type: #FASTTypeScriptTupleType opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ tupleTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> tupleTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	tupleTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeAnnotationOwner [
	"Relation named: #typeAnnotationOwner type: #FASTTypeScriptTypeAnnotation opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ typeAnnotationOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeAnnotationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	typeAnnotationOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeArgumentsOwner [
	"Relation named: #typeArgumentsOwner type: #FASTTypeScriptTypeArguments opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ typeArgumentsOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeArgumentsOwner: anObject [

	<ignoreForCoverage>
	<generated>
	typeArgumentsOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeAssertionOwner [
	"Relation named: #typeAssertionOwner type: #FASTTypeScriptTypeAssertion opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ typeAssertionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeAssertionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	typeAssertionOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeParametersOwner [
	"Relation named: #typeParametersOwner type: #FASTTypeScriptTypeParameters opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ typeParametersOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeParametersOwner: anObject [

	<ignoreForCoverage>
	<generated>
	typeParametersOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeQueryOwner [
	"Relation named: #typeQueryOwner type: #FASTTypeScriptTypeQuery opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ typeQueryOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> typeQueryOwner: anObject [

	<ignoreForCoverage>
	<generated>
	typeQueryOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> unaryExpressionOperatorOwner [
	"Relation named: #unaryExpressionOperatorOwner type: #FASTTypeScriptUnaryExpression opposite: #operator"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ unaryExpressionOperatorOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> unaryExpressionOperatorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	unaryExpressionOperatorOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> unionTypeOwner [
	"Relation named: #unionTypeOwner type: #FASTTypeScriptUnionType opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ unionTypeOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> unionTypeOwner: anObject [

	<ignoreForCoverage>
	<generated>
	unionTypeOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> updateExpressionOperatorOwner [
	"Relation named: #updateExpressionOperatorOwner type: #FASTTypeScriptUpdateExpression opposite: #operator"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ updateExpressionOperatorOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> updateExpressionOperatorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	updateExpressionOperatorOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> variableDeclarationOwner [
	"Relation named: #variableDeclarationOwner type: #FASTTypeScriptVariableDeclaration opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ variableDeclarationOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> variableDeclarationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	variableDeclarationOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> variableDeclaratorNameOwner [
	"Relation named: #variableDeclaratorNameOwner type: #FASTTypeScriptVariableDeclarator opposite: #name"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ variableDeclaratorNameOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> variableDeclaratorNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	variableDeclaratorNameOwner := anObject
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> yieldExpressionOwner [
	"Relation named: #yieldExpressionOwner type: #FASTTypeScriptYieldExpression opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ yieldExpressionOwner
]

{ #category : 'accessing' }
FASTTypeScriptEntity >> yieldExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	yieldExpressionOwner := anObject
]
