Class {
	#name : 'FASTTypeScriptShorthandPropertyIdentifier',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptShorthandPropertyIdentifier class >> annotation [

	<ignoreForCoverage>
	<FMClass: #ShorthandPropertyIdentifier super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
]
