Class {
	#name : 'FASTTypescriptHashBangLine',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptHashBangLine class >> annotation [

	<FMClass: #HashBangLine super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptHashBangLine class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptHash_bang_line }
]
