"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `parentEnum` | `FASTTypescriptProperty_identifier` | `propertyIdentifiers` | `FASTTypescriptEnum_declaration` | The enum that contains me|



"
Class {
	#name : 'FASTTypescriptProperty_identifier',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptProperty_identifier class >> annotation [

	<FMClass: #Property_identifier super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]
