Class {
	#name : 'FASTTypescriptSatisfiesExpression',
	#superclass : 'FASTTypescriptExpression',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptSatisfiesExpression class >> annotation [

	<FMClass: #SatisfiesExpression super: #FASTTypescriptExpression>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptSatisfiesExpression class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptSatisfies_expression }



]
