Class {
	#name : 'FASTTypescriptAugmented_assignment_expression',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptAugmented_assignment_expression class >> annotation [

	<FMClass: #Augmented_assignment_expression super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]
