Class {
	#name : 'FASTTypescriptJsxText',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptJsxText class >> annotation [

	<FMClass: #JsxText super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptJsxText class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptJsx_text }
	

]
