Class {
	#name : 'FASTTypescriptSwitchBody',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptSwitchBody class >> annotation [

	<FMClass: #SwitchBody super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptSwitchBody class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptSwitch_body }
	

]
