Class {
	#name : 'FASTTypescriptTernaryExpression',
	#superclass : 'FASTTypescriptExpression',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptTernaryExpression class >> annotation [

	<FMClass: #TernaryExpression super: #FASTTypescriptExpression>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptTernaryExpression class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptTernary_expression }


]
