Class {
	#name : 'FASTTypescriptAbstract_class_declaration',
	#superclass : 'FASTTypescriptClass_declaration',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptAbstract_class_declaration class >> annotation [

	<FMClass: #Abstract_class_declaration super: #FASTTypescriptClass_declaration>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]
