Class {
	#name : 'FASTTypescriptShorthandPropertyIdentifier',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptShorthandPropertyIdentifier class >> annotation [

	<FMClass: #ShorthandPropertyIdentifier super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptShorthandPropertyIdentifier class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptShorthand_property_identifier }



]
