Class {
	#name : 'FASTTypescriptShorthandPropertyIdentifierPattern',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptShorthandPropertyIdentifierPattern class >> annotation [

	<FMClass: #ShorthandPropertyIdentifierPattern super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptShorthandPropertyIdentifierPattern class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptShorthand_property_identifier_pattern }


]
