Class {
	#name : 'FASTTypescriptElseClause',
	#superclass : 'FASTTypescriptEntity',
	#category : 'FASTTypescript-Model-Entities',
	#package : 'FASTTypescript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypescriptElseClause class >> annotation [

	<FMClass: #ElseClause super: #FASTTypescriptEntity>
	<package: #'FASTTypescript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypescriptElseClause class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptElse_clause}



]
