Class {
	#name : 'FASTTypeScriptAbstractMethodSignature',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptAbstractMethodSignature class >> annotation [

	<FMClass: #AbstractMethodSignature super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptAbstractMethodSignature class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptAbstract_method_signature }
 
 
]
