Class {
	#name : 'FASTTypeScriptTemplateLiteralType',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptTemplateLiteralType class >> annotation [

	<FMClass: #TemplateLiteralType super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptTemplateLiteralType class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptTemplate_literal_type }
 
 
]
