Class {
	#name : 'FASTTypeScriptTernaryExpression',
	#superclass : 'FASTTypeScriptExpression',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptTernaryExpression class >> annotation [

	<FMClass: #TernaryExpression super: #FASTTypeScriptExpression>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptTernaryExpression class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptTernary_expression }

 
 
]
