Class {
	#name : 'FASTTypeScriptSatisfiesExpression',
	#superclass : 'FASTTypeScriptExpression',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptSatisfiesExpression class >> annotation [

	<FMClass: #SatisfiesExpression super: #FASTTypeScriptExpression>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptSatisfiesExpression class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptSatisfies_expression }


 
 
]
