Class {
	#name : 'FASTTypeScriptSpreadElement',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptSpreadElement class >> annotation [

	<FMClass: #SpreadElement super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptSpreadElement class >> initialize [
 
  self deprecatedAliases: { #FASTTypescriptSpread_element }
 
 
]
