Class {
	#name : 'FASTTypeScriptSubscriptExpression',
	#superclass : 'FASTTypeScriptExpression',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptSubscriptExpression class >> annotation [

	<FMClass: #SubscriptExpression super: #FASTTypeScriptExpression>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptSubscriptExpression class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptSubscript_expression }
	
 
 
]
