Class {
	#name : 'FASTTypeScriptForStatement',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptForStatement class >> annotation [

	<FMClass: #ForStatement super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptForStatement class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptFor_statement }
	
 
 
]
