Class {
	#name : 'FASTTypeScriptMethodSignature',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptMethodSignature class >> annotation [

	<FMClass: #MethodSignature super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptMethodSignature class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptMethod_signature }

 
 
]
