Class {
	#name : 'FASTTypeScriptElseClause',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptElseClause class >> annotation [

	<FMClass: #ElseClause super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptElseClause class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptElse_clause}


 
 
]
