"
I am a primary type in Typescript


"
Trait {
	#name : 'FASTTypeScriptTPrimaryType',
	#traits : 'FASTTypeScriptTType',
	#classTraits : 'FASTTypeScriptTType classTrait',
	#category : 'FAST-TypeScript-Model-Traits',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Traits'
}

{ #category : 'meta' }
FASTTypeScriptTPrimaryType classSide >> annotation [

	<ignoreForCoverage>
	<FMClass: #TPrimaryType super: #Object>
	<package: #'FAST-TypeScript-Model'>
	<generated>
]
