Class {
	#name : 'FASTTypeScriptHashBangLine',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptHashBangLine class >> annotation [

	<FMClass: #HashBangLine super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptHashBangLine class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptHash_bang_line }
 
 
]
