Class {
	#name : 'FASTTypeScriptReadonlyType',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptReadonlyType class >> annotation [

	<FMClass: #ReadonlyType super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptReadonlyType class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptReadonly_type }



 
 
]
