Class {
	#name : 'FASTTypeScriptTemplateString',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptTemplateString class >> annotation [

	<FMClass: #TemplateString super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptTemplateString class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptTemplate_string }
 
 
]
