Class {
	#name : 'FASTTypeScriptEscapeSequence',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptEscapeSequence class >> annotation [

	<FMClass: #EscapeSequence super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptEscapeSequence class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptEscape_sequence }

 
 
]
