Class {
	#name : 'FASTTypeScriptShorthandPropertyIdentifierPattern',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptShorthandPropertyIdentifierPattern class >> annotation [

	<FMClass: #ShorthandPropertyIdentifierPattern super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptShorthandPropertyIdentifierPattern class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptShorthand_property_identifier_pattern }

 
 
]
