Class {
	#name : 'FASTTypeScriptRestPattern',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptRestPattern class >> annotation [

	<FMClass: #RestPattern super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptRestPattern class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptRest_pattern }

 
 
]
