Class {
	#name : 'FASTTypeScriptDebuggerStatement',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptDebuggerStatement class >> annotation [

	<FMClass: #DebuggerStatement super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptDebuggerStatement class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptDebugger_statement }

 
 
]
