Class {
	#name : 'FASTTypeScriptInferType',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptInferType class >> annotation [

	<FMClass: #InferType super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptInferType class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptInfer_type }
 
 
]
