Class {
	#name : 'FASTTypeScriptShorthandPropertyIdentifier',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptShorthandPropertyIdentifier class >> annotation [

	<FMClass: #ShorthandPropertyIdentifier super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptShorthandPropertyIdentifier class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptShorthand_property_identifier }


 
 
]
