Class {
	#name : 'FASTTypeScriptOptingTypeAnnotation',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptOptingTypeAnnotation class >> annotation [

	<FMClass: #OptingTypeAnnotation super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptOptingTypeAnnotation class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptOpting_type_annotation }
 
 
]
