Class {
	#name : 'FASTTypeScriptSwitchDefault',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptSwitchDefault class >> annotation [

	<FMClass: #SwitchDefault super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptSwitchDefault class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptSwitch_default }

 
 
]
