Class {
	#name : 'FASTTypeScriptSwitchBody',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptSwitchBody class >> annotation [

	<FMClass: #SwitchBody super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptSwitchBody class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptSwitch_body }
	
 
 
]
