Class {
	#name : 'FASTTypeScriptEnumAssignment',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptEnumAssignment class >> annotation [

	<FMClass: #EnumAssignment super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptEnumAssignment class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptEnum_assignment }
 
 
]
