Class {
	#name : 'FASTTypeScriptIndexTypeQuery',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptIndexTypeQuery class >> annotation [

	<FMClass: #IndexTypeQuery super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptIndexTypeQuery class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptIndex_type_query }
 
 
]
