Class {
	#name : 'FASTTypeScriptNonNullExpression',
	#superclass : 'FASTTypeScriptExpression',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptNonNullExpression class >> annotation [

	<FMClass: #NonNullExpression super: #FASTTypeScriptExpression>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptNonNullExpression class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptNon_null_expression }


 
 
]
