Class {
	#name : 'FASTTypeScriptGeneratorFunctionDeclaration',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptGeneratorFunctionDeclaration class >> annotation [

	<FMClass: #GeneratorFunctionDeclaration super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptGeneratorFunctionDeclaration class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptGenerator_function_declaration }

 
 
]
