Class {
	#name : 'FASTTypeScriptPropertySignature',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptPropertySignature class >> annotation [

	<FMClass: #PropertySignature super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptPropertySignature class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptProperty_signature }
 
 
]
