Class {
	#name : 'FASTTypeScriptJsxText',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptJsxText class >> annotation [

	<FMClass: #JsxText super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptJsxText class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptJsx_text }
	
 
 
]
