Class {
	#name : 'FASTTypeScriptVariableDeclarator',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptVariableDeclarator class >> annotation [

	<FMClass: #VariableDeclarator super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptVariableDeclarator class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptVariable_declarator }
 
 
]
