Class {
	#name : 'FASTTypeScriptAbstractClassDeclaration',
	#superclass : 'FASTTypeScriptClassDeclaration',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptAbstractClassDeclaration class >> annotation [

	<ignoreForCoverage>
	<FMClass: #AbstractClassDeclaration super: #FASTTypeScriptClassDeclaration>
	<package: #'FAST-TypeScript-Model'>
	<generated>
]
