Class {
	#name : 'FASTTypeScriptAssignmentPattern',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptAssignmentPattern class >> annotation [

	<FMClass: #AssignmentPattern super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptAssignmentPattern class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptAssignment_pattern }
 
 
]
