Class {
	#name : 'FASTTypeScriptNestedTypeIdentifier',
	#superclass : 'FASTTypeScriptEntity',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptNestedTypeIdentifier class >> annotation [

	<FMClass: #NestedTypeIdentifier super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'class initialization' }
FASTTypeScriptNestedTypeIdentifier class >> initialize [ 

	self deprecatedAliases: { #FASTTypescriptNested_type_identifier }
 
 
]
