Class {
	#name : 'FASTTypeScriptDebuggerStatement',
	#superclass : 'FASTTypeScriptStatement',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptDebuggerStatement class >> annotation [

	<ignoreForCoverage>
	<FMClass: #DebuggerStatement super: #FASTTypeScriptStatement>
	<package: #'FAST-TypeScript-Model'>
	<generated>
]
