name: Continuous

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-12, Pharo64-13, Pharo64-14, Moose64-12 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v7
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        if: ${{ matrix.smalltalk == 'Pharo64-12' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./coverage/lcov.info
          format: lcov
